//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentProtocolServiceSystemAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApartmentProtocolServiceSystemFinalEntities : DbContext
    {
        public ApartmentProtocolServiceSystemFinalEntities()
            : base("name=ApartmentProtocolServiceSystemFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<building_staff> building_staff { get; set; }
        public virtual DbSet<Buildings_expenses> Buildings_expenses { get; set; }
        public virtual DbSet<daily_inout_record> daily_inout_record { get; set; }
        public virtual DbSet<flat_member> flat_member { get; set; }
        public virtual DbSet<guest> guests { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<notice_board> notice_board { get; set; }
        public virtual DbSet<rent_holder> rent_holder { get; set; }
        public virtual DbSet<rentHolders_member> rentHolders_member { get; set; }
        public virtual DbSet<rentHolders_servant> rentHolders_servant { get; set; }
        public virtual DbSet<servant> servants { get; set; }
        public virtual DbSet<service_charge_payment_record> service_charge_payment_record { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
