//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentProtocolServiceSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class building_staff
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string fathersname { get; set; }
        public string type { get; set; }
        public string phonenumber { get; set; }
        public string nidnumber { get; set; }
        public System.DateTime dateofbirth { get; set; }
        public string photo { get; set; }
        public string salary { get; set; }
        public int manager_id { get; set; }
        public string status { get; set; }
    
        public virtual user user { get; set; }
    }
}
