//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentProtocolServiceSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buildings_expenses
    {
        public int id { get; set; }
        public string slot { get; set; }
        public string ammount { get; set; }
        public System.DateTime date { get; set; }
        public string managers_name { get; set; }
    }
}
