//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentProtocolServiceSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_inout_record
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string flat_no { get; set; }
        public string type { get; set; }
        public System.DateTime entry_time { get; set; }
        public Nullable<System.DateTime> exit_time { get; set; }
        public string duty_guard { get; set; }
    }
}
