//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentProtocolServiceSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string type { get; set; }
        public string qsn { get; set; }
        public string ans { get; set; }
    }
}
