//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentProtocolServiceSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notice_board
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string tittle { get; set; }
        public string details { get; set; }
        public string attachment { get; set; }
    }
}
