//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentProtocolServiceSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_charge_payment_record
    {
        public int id { get; set; }
        public string flat_no { get; set; }
        public System.DateTime month { get; set; }
        public string payment_type { get; set; }
        public string ammount { get; set; }
        public string reciver_name { get; set; }
    }
}
