//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentProtocolServiceSystemAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class user
    {
        public user()
        {
            this.building_staff = new HashSet<building_staff>();
            this.flat_member = new HashSet<flat_member>();
            this.rent_holder = new HashSet<rent_holder>();
            this.servants = new HashSet<servant>();
        }
    
        public int id { get; set; }
        public string fullname { get; set; }
        public string fathersname { get; set; }
        public string flat_no { get; set; }
        public string type { get; set; }
        public string phonenumber { get; set; }
        public string nidnumber { get; set; }
        public System.DateTime dateofbirth { get; set; }
        public string email { get; set; }
        public bool isemailveryfied { get; set; }
        public System.Guid activationcode { get; set; }
        public string password { get; set; }
        public string photo { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<building_staff> building_staff { get; set; }
        [JsonIgnore, XmlIgnore] public virtual ICollection<flat_member> flat_member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rent_holder> rent_holder { get; set; }
        [JsonIgnore, XmlIgnore] public virtual ICollection<servant> servants { get; set; }
    }
}
